const GameState = { currentScreen: 'intro', playerName: '', stage: 1, score: 0, lives: 4, maxLives: 4, goldenPouches: 0, maxPouches: 7, ammo: 30, enemiesDefeated: 0, resourcesCollected: 0, stagesCleared: 0, isFrozen: false, isPaused: false, gameRunning: false };
const Config = { canvasWidth: 800, canvasHeight: 600, playerSpeed: 7, bulletSpeed: 12, enemyBaseSpeed: 0.575, stageSpeedIncrease: 0.115, stageHealthMultiplier: 1, freezeDuration: 5000, bossStages: [5, 10, 15, 20], stage1EnemyCount: 2, enemyIncreasePerStage: 1, invincibilityDuration: 120, itemSpeedBoost: 0.02 };
let player = null, enemies = [], items = [], bullets = [], particles = [], tunnelTrail = [], bgDots = [], bgStones = [], bgRoots = [], bgLeaves = [], bgSeeds = [], bgWormTunnels = [], canvas, ctx, deferredPrompt;
const screens = {}, elements = {};
document.addEventListener('DOMContentLoaded', () => { initializeElements(); initializeCanvas(); createLogoAnimation(); createIntroMole(); setupEventListeners(); populateRankings(); initializeLives(); initializePouches(); });
function initializeElements() { screens.intro = document.getElementById('intro-screen'); screens.character = document.getElementById('character-intro'); screens.ranking = document.getElementById('ranking-screen'); screens.game = document.getElementById('game-screen'); screens.complete = document.getElementById('stage-complete'); screens.gameover = document.getElementById('game-over'); screens.boss = document.getElementById('boss-screen'); elements.logoText = document.getElementById('logo-text'); elements.introMole = document.getElementById('intro-mole'); elements.digulHero = document.getElementById('digul-hero'); elements.rankingList = document.getElementById('ranking-list'); elements.playerName = document.getElementById('player-name'); elements.playerPassword = document.getElementById('player-password'); elements.stageNumber = document.getElementById('stage-number'); elements.scoreValue = document.getElementById('score-value'); elements.ammoCount = document.getElementById('ammo-count'); elements.livesContainer = document.getElementById('lives-container'); elements.goldenPouches = document.getElementById('golden-pouches'); elements.freezeOverlay = document.getElementById('freeze-overlay'); elements.enemiesDefeated = document.getElementById('enemies-defeated'); elements.resourcesCollected = document.getElementById('resources-collected'); elements.stageScore = document.getElementById('stage-score'); elements.finalScore = document.getElementById('final-score'); elements.stagesCleared = document.getElementById('stages-cleared'); elements.btnInstall = document.getElementById('btn-install'); }
function initializeCanvas() { canvas = document.getElementById('game-canvas'); ctx = canvas.getContext('2d'); resizeCanvas(); window.addEventListener('resize', resizeCanvas); }
function resizeCanvas() { const targetRatio = 800 / 600; const windowRatio = window.innerWidth / window.innerHeight; if (windowRatio > targetRatio) { canvas.style.height = '100vh'; canvas.style.width = 'auto'; } else { canvas.style.width = '100vw'; canvas.style.height = 'auto'; } canvas.width = 800; canvas.height = 600; }
function setupEventListeners() { document.getElementById('btn-start').addEventListener('click', () => showScreen('character')); document.getElementById('btn-continue').addEventListener('click', () => showScreen('ranking')); document.getElementById('btn-play').addEventListener('click', startGame); document.getElementById('btn-next')?.addEventListener('click', nextStage); document.getElementById('btn-retry')?.addEventListener('click', retryGame); document.getElementById('btn-home')?.addEventListener('click', () => showScreen('intro')); document.addEventListener('keydown', e => { keys[e.code] = true; if(GameState.gameRunning) { if(e.code === 'Space') { e.preventDefault(); shootBullet(); } if(e.code === 'KeyZ') player.isDigging = true; } }); document.addEventListener('keyup', e => { keys[e.code] = false; if(e.code === 'KeyZ' && player) player.isDigging = false; }); canvas.addEventListener('touchstart', e => { e.preventDefault(); const touch = e.touches[0]; if (touch.clientY > window.innerHeight * 0.7) player.isDigging = true; if (touch.clientY < window.innerHeight * 0.3) shootBullet(); touchStartX = touch.clientX; touchStartY = touch.clientY; }, { passive: false }); canvas.addEventListener('touchmove', e => { e.preventDefault(); const touch = e.touches[0]; const dx = touch.clientX - touchStartX, dy = touch.clientY - touchStartY, threshold = 30; keys['ArrowLeft'] = keys['ArrowRight'] = keys['ArrowUp'] = keys['ArrowDown'] = false; if (Math.abs(dx) > threshold) dx > 0 ? keys['ArrowRight'] = true : keys['ArrowLeft'] = true; if (Math.abs(dy) > threshold) dy > 0 ? keys['ArrowDown'] = true : keys['ArrowUp'] = true; }, { passive: false }); canvas.addEventListener('touchend', e => { e.preventDefault(); player.isDigging = false; keys['ArrowLeft'] = keys['ArrowRight'] = keys['ArrowUp'] = keys['ArrowDown'] = false; }); }
function showScreen(id) { Object.values(screens).forEach(s => s?.classList.remove('active')); screens[id]?.classList.add('active'); GameState.currentScreen = id; }
function startGame() { if (!elements.playerName?.value.trim()) return; resetGameState(); showScreen('game'); initializeGame(); }
function resetGameState() { GameState.stage = 1; GameState.score = 0; GameState.lives = 4; GameState.goldenPouches = 0; GameState.ammo = 30; GameState.enemiesDefeated = 0; GameState.resourcesCollected = 0; GameState.stagesCleared = 0; GameState.gameRunning = true; }
function initializeGame() { player = { x: 400, y: 300, width: 60, height: 80, speed: 7, direction: 'right', isDigging: false, isInvincible: false, invincibilityTimer: 0, blinkTimer: 0, digAnimTimer: 0, vx: 0, vy: 0 }; enemies = []; items = []; bullets = []; particles = []; tunnelTrail = []; generateBackgroundElements(); spawnStageContent(); updateUI(); if (GameState.gameRunning) requestAnimationFrame(gameLoop); }
function gameLoop() { if (!GameState.gameRunning) return; update(); render(); requestAnimationFrame(gameLoop); }
function update() { updatePlayer(); updateEnemies(); updateBullets(); checkCollisions(); if (enemies.length === 0 && GameState.gameRunning) stageComplete(); }
function updatePlayer() { if (!player) return; if (player.isInvincible) if (--player.invincibilityTimer <= 0) player.isInvincible = false; player.vx = player.vy = 0; if (keys['ArrowLeft'] || keys['KeyA']) { player.vx = -7; player.direction = 'left'; } if (keys['ArrowRight'] || keys['KeyD']) { player.vx = 7; player.direction = 'right'; } if (keys['ArrowUp'] || keys['KeyW']) player.vy = -7; if (keys['ArrowDown'] || keys['KeyS']) player.vy = 7; player.x = Math.max(0, Math.min(800 - 60, player.x + player.vx)); player.y = Math.max(80, Math.min(600 - 80 - 50, player.y + player.vy)); if (player.vx || player.vy) { if (++player.digAnimTimer % 3 === 0) tunnelTrail.push({ x: player.x + 30, y: player.y + 40, size: 35, alpha: 0.6 }); } tunnelTrail = tunnelTrail.filter(t => (t.alpha -= 0.008) > 0); }
function updateEnemies() { enemies.forEach(e => { if (e.isFrozen) if (--e.frozenTimer <= 0) e.isFrozen = false; else return; const dx = player.x - e.x, dy = player.y - e.y, dist = Math.sqrt(dx*dx + dy*dy); if (dist > 0) { e.x += (dx/dist)*e.speed; e.y += (dy/dist)*e.speed; } }); }
function updateBullets() { bullets = bullets.filter(b => { b.x += b.dirX * b.speed; return b.x > 0 && b.x < 800; }); }
function checkCollisions() { items = items.filter(it => isColliding(player, it) ? (collectItem(it), false) : true); bullets.forEach((b, bi) => { enemies.forEach((e, ei) => { if (isCollidingCircleRect(b, e)) { if (--e.health <= 0) { enemies.splice(ei, 1); GameState.score += 100; } bullets.splice(bi, 1); } }); }); if (!GameState.isFrozen && !player.isInvincible) enemies.forEach(e => { if (isColliding(player, e)) playerHit(); }); }
function isColliding(a, b) { return a.x < b.x + b.width && a.x + a.width > b.x && a.y < b.y + b.height && a.y + a.height > b.y; }
function isCollidingCircleRect(c, r) { const x = Math.max(r.x, Math.min(c.x, r.x+r.width)), y = Math.max(r.y, Math.min(c.y, r.y+r.height)), dx = c.x-x, dy = c.y-y; return dx*dx + dy*dy < c.radius*c.radius; }
function collectItem(it) { GameState.score += 50; if (it.type === 'golden-pouch') if (++GameState.goldenPouches >= 7) activateFreeze(); updateUI(); }
function playerHit() { if (--GameState.lives <= 0) gameOver(); else { player.isInvincible = true; player.invincibilityTimer = 120; player.x = 400; player.y = 300; } updateUI(); }
function activateFreeze() { GameState.isFrozen = true; GameState.goldenPouches = 0; elements.freezeOverlay?.classList.remove('hidden'); enemies.forEach(e => { e.isFrozen = true; e.frozenTimer = 300; }); setTimeout(() => { GameState.isFrozen = false; elements.freezeOverlay?.classList.add('hidden'); }, 5000); }
function stageComplete() { GameState.gameRunning = false; GameState.stagesCleared++; showScreen('complete'); }
function nextStage() { GameState.stage++; GameState.gameRunning = true; showScreen('game'); initializeGame(); }
function gameOver() { GameState.gameRunning = false; showScreen('gameover'); }
function retryGame() { resetGameState(); showScreen('game'); initializeGame(); }
function render() { ctx.clearRect(0,0,800,600); drawBackground(); drawTunnelTrail(); drawItems(); drawEnemies(); drawBullets(); drawPlayer(); }
function drawPlayer() { if (!player || (player.isInvincible && Math.floor(Date.now()/100)%2)) return; ctx.fillStyle = '#8B6914'; ctx.fillRect(player.x, player.y, 60, 80); }
function drawEnemies() { enemies.forEach(e => { ctx.fillStyle = e.type === 'boar' ? '#4A4A4A' : '#D2691E'; ctx.fillRect(e.x, e.y, e.width, e.height); }); }
function drawItems() { items.forEach(it => { ctx.fillStyle = '#FFD700'; ctx.beginPath(); ctx.arc(it.x+15, it.y+15, 15, 0, Math.PI*2); ctx.fill(); }); }
function drawBullets() { bullets.forEach(b => { ctx.fillStyle = '#8B4513'; ctx.beginPath(); ctx.arc(b.x, b.y, 8, 0, Math.PI*2); ctx.fill(); }); }
function drawBackground() { ctx.fillStyle = '#5A4030'; ctx.fillRect(0, 0, 800, 600); }
function drawTunnelTrail() { tunnelTrail.forEach(t => { ctx.globalAlpha = t.alpha; ctx.fillStyle = '#2A1810'; ctx.beginPath(); ctx.arc(t.x, t.y, t.size, 0, Math.PI*2); ctx.fill(); ctx.globalAlpha = 1; }); }
function spawnStageContent() { for(let i=0; i<2+GameState.stage; i++) enemies.push({ x: Math.random()*700, y: Math.random()*500, width: 50, height: 50, type: 'wildcat', health: 1, maxHealth: 1, speed: 0.6+GameState.stage*0.1 }); for(let i=0; i<10; i++) items.push({ x: Math.random()*700, y: Math.random()*500, width: 30, height: 30, type: 'gold' }); }
function updateUI() { if(elements.stageNumber) elements.stageNumber.textContent = GameState.stage; if(elements.scoreValue) elements.scoreValue.textContent = GameState.score; }
function createLogoAnimation() {} function createIntroMole() {} function populateRankings() {} function initializeLives() {} function initializePouches() {} function generateBackgroundElements() {}
const keys = {};